services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file: .env
    expose:
      - 3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file: .env
    expose:
      - 9000
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/dlacuey/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/dlacuey/data/wordpress'

networks:
  inception:
    driver: bridge
